[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/Art-wall/artwall_main.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/Art-wall/artwall_main.html"
  status = 200